grammar <- sp rule+ !.
rule <- identifier sp '<-' sp pattern
pattern <- alternative ( '/' !'/' sp alternative )*
alternative <- lookahead+
lookop <- [!&]
lookahead <- (lookop sp)? suffix
countop <- [*+?]
suffix <- primary (countop sp)*
primary <- ( '(' sp pattern ')' / any / literal / class / call ) sp
any <- '.'
literal <- ['] ( !['] . )* [']
class <- '[' ( !']' ( . '-' . / . ) )* ']'
call <- identifier !(sp '<-')
identifier <- [a-zA-Z0-9_]+
sp <- ( [ \t\r\n] / '//' ( ![\r\n] . )* )*
